admin_password: admin
version: latest
ROS_version: 1.5.6
# Empty defaults to latest non-experimental available
k8s_version: ""
server:
  cpus: 1
  memory: 4096
node:
  count: 2
  cpus: 2
  memory: 3500

ip:

  server: 172.22.101.101
  node: 172.22.101.110
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: private_network
